### ISSUE TITLE
settings-production.py misconfiguring redis broker

### ISSUE THREAD

**Issue by cromulus** [praekeltfoundation/casepro#229]
```
2019-05-10T17:05:30.437400194Z app[web.1]: [2019-05-10 17:05:29,975: CRITICAL/MainProcess] Unrecoverable error: SyntaxError('invalid syntax', ('/usr/local/lib/python3.7/site-packages/celery/backends/redis.py', 22, 19, 'from . import async, base\n'))
2019-05-10T17:05:30.437404831Z app[web.1]: Traceback (most recent call last):
2019-05-10T17:05:30.437408872Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
2019-05-10T17:05:30.437413841Z app[web.1]:     return obj.__dict__[self.__name__]
2019-05-10T17:05:30.437417662Z app[web.1]: KeyError: 'backend'
2019-05-10T17:05:30.437421446Z app[web.1]:
2019-05-10T17:05:30.437425063Z app[web.1]: During handling of the above exception, another exception occurred:
2019-05-10T17:05:30.437428915Z app[web.1]:
2019-05-10T17:05:30.437432718Z app[web.1]: Traceback (most recent call last):
2019-05-10T17:05:30.437437099Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
2019-05-10T17:05:30.437441509Z app[web.1]:     self.blueprint.start(self)
2019-05-10T17:05:30.437445517Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 115, in start
2019-05-10T17:05:30.437449697Z app[web.1]:     self.on_start()
2019-05-10T17:05:30.437453570Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 139, in on_start
2019-05-10T17:05:30.437457514Z app[web.1]:     self.emit_banner()
2019-05-10T17:05:30.437461100Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 154, in emit_banner
2019-05-10T17:05:30.437464873Z app[web.1]:     ' \n', self.startup_info(artlines=not use_image))),
2019-05-10T17:05:30.437468609Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 217, in startup_info
2019-05-10T17:05:30.437472370Z app[web.1]:     results=self.app.backend.as_uri(),
2019-05-10T17:05:30.437485413Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
2019-05-10T17:05:30.437490129Z app[web.1]:     value = obj.__dict__[self.__name__] = self.__get(obj)
2019-05-10T17:05:30.437493740Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 1196, in backend
2019-05-10T17:05:30.437497542Z app[web.1]:     return self._get_backend()
2019-05-10T17:05:30.437505131Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 914, in _get_backend
2019-05-10T17:05:30.437509569Z app[web.1]:     self.loader)
2019-05-10T17:05:30.437512957Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 70, in by_url
2019-05-10T17:05:30.437516850Z app[web.1]:     return by_name(backend, loader), url
2019-05-10T17:05:30.437520354Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 50, in by_name
2019-05-10T17:05:30.437524127Z app[web.1]:     cls = symbol_by_name(backend, aliases)
2019-05-10T17:05:30.437527874Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
2019-05-10T17:05:30.437531799Z app[web.1]:     module = imp(module_name, package=package, **kwargs)
2019-05-10T17:05:30.437535237Z app[web.1]:   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
2019-05-10T17:05:30.437539015Z app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2019-05-10T17:05:30.437542392Z app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2019-05-10T17:05:30.437546469Z app[web.1]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2019-05-10T17:05:30.437550624Z app[web.1]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2019-05-10T17:05:30.437554896Z app[web.1]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2019-05-10T17:05:30.437558787Z app[web.1]:   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
2019-05-10T17:05:30.437562714Z app[web.1]:   File "<frozen importlib._bootstrap_external>", line 860, in get_code
2019-05-10T17:05:30.437566519Z app[web.1]:   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
2019-05-10T17:05:30.437570483Z app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-05-10T17:05:30.437574538Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 22
2019-05-10T17:05:30.437578313Z app[web.1]:     from . import async, base
2019-05-10T17:05:30.437582001Z app[web.1]:                       ^
2019-05-10T17:05:30.437585399Z app[web.1]: SyntaxError: invalid syntax
2019-05-10T17:05:30.437588659Z app[web.1]: 2019-05-10 17:05:29,468 INFO exited: web (exit status 1; not expected)
2019-05-10T17:05:30.437592162Z app[web.1]: 2019-05-10 17:05:29,980 INFO spawned: 'web' with pid 3530
2019-05-10T17:05:30.437595659Z app[web.1]: 2019-05-10 17:05:30,231 INFO exited: celery-beat (exit status 1; not expected)
```

This is using the Dockerfile, with Redis running on localhost, and the environment variable unset. Essentially, something about how we are configuring Redis is preventing the app from starting.

**Comment by rudigiesler** [comment]
The way this docker image works is that there is a supervisor running inside of it, which runs the web worker, redis, celery beat, and celery: https://github.com/praekeltfoundation/casepro/blob/develop/docker/supervisor.conf

This is not ideal, and something that we would like to change: being able to run separate containers for each of those components.

I'm really not sure what is causing the error you're getting above though, that seems like an error in celery, not the same error I've seen if celery can't connect to redis. I'm wondering if a version of a dependency is not being pinned properly somewhere, so a new version of something has been released and so building the image is pulling that new version

**Comment by cromulus** [comment]
This is what they use in the standard rapidpro docker setup:
[https://github.com/rapidpro/rapidpro-docker/blob/master/stack/startup.sh](https://github.com/rapidpro/rapidpro-docker/blob/master/stack/startup.sh)

Uses an environment variable to determine what sort of process to run.

Also, ideally, redis should be a backing service and not included in the base image. Python isn't my jam, but a syntax error seems strange here. It looks like it is coming from a dependency.

**Comment by rudigiesler** [comment]
Yes, this docker image is due for an overhaul. I've laid out what needs to be done in three issues https://github.com/praekeltfoundation/casepro/issues/230 https://github.com/praekeltfoundation/casepro/issues/231 https://github.com/praekeltfoundation/casepro/issues/232 . Ideally, we would have a separate casepro-docker repo, which contains all of the docker-specific things, and just pulls the code from upstream into the docker image. We can then also do things like CI unit testing on the docker image to ensure that it's a working image, to avoid problems like this, and also push the built image to docker hub.

Yes, this seems to be coming from the `celery` dependancy. Looking at https://github.com/celery/celery/issues/4849 , this seems to be an issue related to python 3.7, I know that last time I looked, there was no python 3.7 support for celery, you had to run python 3.6

Was this error maybe from when the base image was set to `latest`, instead of `py3.6-stretch`?

**Comment by rudigiesler** [comment]
In our docker bootstrap image we have a similar entrypoint https://github.com/praekeltfoundation/docker-django-bootstrap/blob/develop/django-entrypoint.sh , we use the command args to determine what kind of process to run.

**Comment by cromulus** [comment]
Using py3.6-stretch fixes this issue...
